name: MiddCraft
description: A custom plugin for MiddCraft
version: 1.0.0-SNAPSHOT
main: com.middcraft.middcraft.MiddCraft
authors: [Picajoluna]
permissions:
  middcraft.chat:
    description: gives permission to send messages in the chat
    default: op